version: '3.4'

services:

  messenger:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  cache:
    image: memcached

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - SESSION_SECRET=${ENV_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017
      - LC=${LC_ENV}
      - EXP=${EXP_ENV}
    depends_on:
      - messenger
      - zookeeper
      - cache
    links:
      - messenger
      - zookeeper
      - cache
    ports:
      - 6001:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-paris:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - PYTHONUNBUFFERED=1
    depends_on:
      - messenger
      - cache
    links:
      - messenger
      - cache
    command: python consumer.py

  bangalore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/bangalore:/usr/data"
    environment:
      - WHOAMI=bangalore
      - SESSION_SECRET=${ENV_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017     
      - LC=${LC_ENV}
      - EXP=${EXP_ENV}
    depends_on:
      - messenger
      - zookeeper
      - cache
    links:
      - messenger
      - zookeeper
      - cache
    ports:
      - 6002:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-bangalore:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
      - "./data/bangalore:/usr/data"
    environment:
      - WHOAMI=bangalore
      - PYTHONUNBUFFERED=1
    depends_on:
      - messenger
      - cache
    links:
      - messenger
      - cache
    command: python consumer.py

  newyork:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/newyork:/usr/data"
    environment:
      - WHOAMI=newyork
      - SESSION_SECRET=${ENV_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017
      - LC=${LC_ENV}
      - EXP=${EXP_ENV}
    depends_on:
      - messenger
      - zookeeper
      - cache
    links:
      - messenger
      - zookeeper
      - cache
    ports:
      - 6003:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-newyork:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
      - "./data/newyork:/usr/data"
    environment:
      - WHOAMI=newyork
      - PYTHONUNBUFFERED=1
    depends_on:
      - messenger
      - cache
    links:
      - messenger
      - cache
    command: python consumer.py
