version: '3.4'

services:

  messenger:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
    environment:
      - WHOAMI=paris
      - SESSION_SECRET=${ENV_VAYPA_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017
    depends_on:
      - messenger
    links:
      - messenger
    ports:
      - 6001:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-paris:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
    environment:
      - WHOAMI=paris
      - PYTHONUNBUFFERED=1

  bangalore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
    environment:
      - WHOAMI=bangalore
      - SESSION_SECRET=${ENV_VAYPA_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017
    depends_on:
      - messenger
    links:
      - messenger
    ports:
      - 6002:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-bangalore:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
    environment:
      - WHOAMI=bangalore
      - PYTHONUNBUFFERED=1

  newyork:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
    environment:
      - WHOAMI=newyork
      - SESSION_SECRET=${ENV_VAYPA_SESSION_SECRET}
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - RABBIT_URL=mongodb://mongo:27017
    depends_on:
      - messenger
    links:
      - messenger
    ports:
      - 6003:6000
    command: flask run --host=0.0.0.0 --port=6000

  worker-newyork:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "./worker:/usr/src/app"
    environment:
      - WHOAMI=newyork
      - PYTHONUNBUFFERED=1
